'use strict';

/* Easy Lights.

   The maths matters here, so it is worth stating. Pressing a cell toggles it and
   its four orthogonal neighbours, and toggling is addition modulo 2, so the whole
   puzzle is a linear system over GF(2): A x = b, where x says which cells to
   press and b is the pattern of lit cells.

   Two consequences drive the implementation:

   - For the 5x5 grid, A has a 2 dimensional null space, meaning two non-trivial
     "quiet patterns" of presses that change nothing. Only one configuration in
     four is solvable, and every solvable one has exactly four solutions.
     So a puzzle is NEVER generated by randomising lights. It is generated by
     applying random presses to a solved board, which is solvable by construction.

   - Press order never matters, only whether each cell is pressed an odd number
     of times. That makes the minimum press count well defined, and we compute it
     by Gaussian elimination plus enumerating the null space. */

(function () {
  const SIZE = 520;

  let N = 5;
  let lights = [];          // 0 or 1 per cell
  let presses = 0;
  let minimum = 0;          // fewest presses that solve the current board
  let state = 'menu';       // menu | play | won
  let flash = [];           // click feedback
  let hintCell = -1;
  let showSolution = false;
  let solution = [];
  let startMinimum = 0;

  Shell.mount({
    name: 'Lights',
    width: SIZE, height: SIZE, max: 520, pad: 260,
    tools: ['sound', 'help'],
    foot: 'Click or tap a light &middot; <b>H</b> for a hint &middot; <b>R</b> for a new puzzle',
    rules: `
      <ul>
        <li>Pressing a cell flips it <b>and</b> its four neighbours, in a plus shape.</li>
        <li>Turn every light off to win.</li>
        <li>The order you press in does not matter, only whether each cell gets
            pressed an odd number of times. So there is always a shortest answer.</li>
        <li>Every puzzle here is solvable. That is not automatic: on a 5x5 grid only
            one random light pattern in four can ever be solved, so these are built
            by scrambling a solved board instead.</li>
      </ul>
      <p>The press counter shows how close you are to the shortest possible
         solution, which the hint button works from.</p>`
  });

  Input.init();
  Input.claim(['KeyH', 'KeyR', 'KeyS']);
  const ctx = Shell.ctx;

  /* ---------- toggling ---------- */

  const idx = (r, c) => r * N + c;

  function pressAt(arr, r, c) {
    arr[idx(r, c)] ^= 1;
    if (r > 0) arr[idx(r - 1, c)] ^= 1;
    if (r < N - 1) arr[idx(r + 1, c)] ^= 1;
    if (c > 0) arr[idx(r, c - 1)] ^= 1;
    if (c < N - 1) arr[idx(r, c + 1)] ^= 1;
  }

  /* ---------- GF(2) solver ---------- */

  /** Bitmask of the cells a press at cell i toggles. */
  function pressMask(i) {
    const r = Math.floor(i / N), c = i % N;
    let m = 0n;
    const set = (rr, cc) => { m |= 1n << BigInt(rr * N + cc); };
    set(r, c);
    if (r > 0) set(r - 1, c);
    if (r < N - 1) set(r + 1, c);
    if (c > 0) set(r, c - 1);
    if (c < N - 1) set(r, c + 1);
    return m;
  }

  /**
   * Solve A x = b over GF(2) and return the minimum weight solution, or null if
   * unsolvable. Rows are BigInts: bits 0..n-1 are the matrix, bit n is the RHS.
   */
  function solve(b) {
    const n = N * N;
    const RHS = BigInt(n);
    const cols = [];
    for (let j = 0; j < n; j++) cols.push(pressMask(j));

    // Row i of the system says: the parity of presses touching cell i equals b[i].
    const rows = [];
    for (let i = 0; i < n; i++) {
      let row = 0n;
      for (let j = 0; j < n; j++) if ((cols[j] >> BigInt(i)) & 1n) row |= 1n << BigInt(j);
      if (b[i]) row |= 1n << RHS;
      rows.push(row);
    }

    // Forward elimination.
    const pivotOf = new Array(n).fill(-1);   // column -> row
    let r = 0;
    for (let col = 0; col < n && r < n; col++) {
      let sel = -1;
      for (let i = r; i < n; i++) if ((rows[i] >> BigInt(col)) & 1n) { sel = i; break; }
      if (sel === -1) continue;
      const t = rows[r]; rows[r] = rows[sel]; rows[sel] = t;
      for (let i = 0; i < n; i++) {
        if (i !== r && ((rows[i] >> BigInt(col)) & 1n)) rows[i] ^= rows[r];
      }
      pivotOf[col] = r;
      r++;
    }

    // Inconsistent if some row is 0 = 1.
    for (let i = 0; i < n; i++) {
      const lhs = rows[i] & ((1n << RHS) - 1n);
      if (lhs === 0n && ((rows[i] >> RHS) & 1n)) return null;
    }

    const free = [];
    for (let col = 0; col < n; col++) if (pivotOf[col] === -1) free.push(col);

    const build = (freeVals) => {
      const x = new Array(n).fill(0);
      free.forEach((col, k) => { x[col] = freeVals[k]; });
      for (let col = n - 1; col >= 0; col--) {
        const row = pivotOf[col];
        if (row === -1) continue;
        let v = Number((rows[row] >> RHS) & 1n);
        for (let j = col + 1; j < n; j++) {
          if ((rows[row] >> BigInt(j)) & 1n) v ^= x[j];
        }
        x[col] = v;
      }
      return x;
    };

    // Enumerate the null space to find the shortest solution. The dimension is
    // 2 for 5x5 and 4 for 4x4, so this is a handful of candidates.
    const k = free.length;
    if (k > 14) return build(new Array(k).fill(0));
    let bestX = null, bestW = Infinity;
    for (let mask = 0; mask < (1 << k); mask++) {
      const vals = [];
      for (let i = 0; i < k; i++) vals.push((mask >> i) & 1);
      const x = build(vals);
      const w = x.reduce((a, v) => a + v, 0);
      if (w < bestW) { bestW = w; bestX = x; }
    }
    return bestX;
  }

  function recomputeSolution() {
    solution = solve(lights) || [];
    minimum = solution.reduce((a, v) => a + v, 0);
  }

  /* ---------- game flow ---------- */

  function newPuzzle(n) {
    N = n || N;
    lights = new Array(N * N).fill(0);
    // Scramble from solved, so solvability is guaranteed by construction.
    const wanted = Math.max(3, Math.round(N * N * 0.34));
    const pressed = new Set();
    while (pressed.size < wanted) pressed.add(randInt(N * N));
    for (const i of pressed) pressAt(lights, Math.floor(i / N), i % N);
    // A scramble can cancel out to an already solved board; reroll if so.
    if (lights.every((v) => !v)) return newPuzzle(N);

    presses = 0;
    hintCell = -1;
    showSolution = false;
    flash = [];
    recomputeSolution();
    startMinimum = minimum;          // remembered so the win card can compare
    state = 'play';
    Shell.hide();
    updateHud();
  }

  function click(r, c) {
    if (state !== 'play') return;
    pressAt(lights, r, c);
    presses++;
    flash.push({ r, c, t: 0 });
    hintCell = -1;
    Sfx.place();
    recomputeSolution();
    updateHud();
    if (lights.every((v) => !v)) win();
  }

  function win() {
    state = 'won';
    Sfx.win();
    const res = Scores.submit('lights', presses, { variant: 'n' + N, lower: true });
    Shell.gameOverCard({
      title: 'All out',
      scoreLabel: 'Presses used',
      score: presses,
      isNew: res.isNew && res.previous !== null,
      best: Scores.label('lights', 'n' + N),
      extra: `<p class="tag" style="margin-top:8px">${
        presses === startMinimum ? 'That is the shortest possible solution.'
        : 'The shortest solution for that board was ' + startMinimum + '.'}</p>`,
      buttons: [{ label: 'New puzzle', act: 'again', primary: true }, { label: 'Change size', act: 'menu' }]
    });
  }

  function updateHud() {
    Shell.readouts([
      { label: 'Presses', value: presses, accent: true },
      { label: 'Lit', value: lights.reduce((a, v) => a + v, 0) },
      { label: 'Left to go', value: minimum },
      { label: 'Best', value: Scores.label('lights', 'n' + N) }
    ]);
    Shell.status(presses, N + 'x' + N + ' grid');
  }

  /* ---------- input ---------- */

  function cellAt(px, py) {
    const m = metrics();
    const c = Math.floor((px - m.pad) / (m.tile + m.gap));
    const r = Math.floor((py - m.pad) / (m.tile + m.gap));
    if (r < 0 || c < 0 || r >= N || c >= N) return null;
    return { r, c };
  }

  Shell.canvas.addEventListener('pointerdown', (e) => {
    const p = Touch.canvasPos(Shell.canvas, e);
    const cell = cellAt(p.x, p.y);
    if (cell) click(cell.r, cell.c);
  });

  window.addEventListener('keydown', (e) => {
    if (state === 'menu') return;
    if (e.code === 'KeyR') newPuzzle(N);
    if (e.code === 'KeyH' && state === 'play') {
      const opts = solution.map((v, i) => (v ? i : -1)).filter((i) => i >= 0);
      if (opts.length) { hintCell = pick(opts); Sfx.tick(false); }
    }
    if (e.code === 'KeyS' && state === 'play') showSolution = !showSolution;
  });

  /* ---------- drawing ---------- */

  function metrics() {
    const gap = N <= 4 ? 14 : (N === 5 ? 12 : 10);
    const pad = 26;
    const tile = (SIZE - pad * 2 - gap * (N - 1)) / N;
    return { gap, pad, tile };
  }

  function draw(dt) {
    for (let i = flash.length - 1; i >= 0; i--) {
      flash[i].t += (dt || 0.016) * 5;
      if (flash[i].t >= 1) flash.splice(i, 1);
    }

    const m = metrics();
    ctx.fillStyle = '#181f2f';
    ctx.fillRect(0, 0, SIZE, SIZE);

    for (let r = 0; r < N; r++) {
      for (let c = 0; c < N; c++) {
        const x = m.pad + c * (m.tile + m.gap);
        const y = m.pad + r * (m.tile + m.gap);
        const on = lights[idx(r, c)] === 1;
        const f = flash.find((q) => q.r === r && q.c === c);

        if (on) {
          const glow = ctx.createRadialGradient(x + m.tile / 2, y + m.tile / 2, m.tile * 0.1,
                                                x + m.tile / 2, y + m.tile / 2, m.tile * 0.95);
          glow.addColorStop(0, 'rgba(255,196,77,.55)');
          glow.addColorStop(1, 'rgba(255,176,46,0)');
          ctx.fillStyle = glow;
          ctx.fillRect(x - m.tile * 0.45, y - m.tile * 0.45, m.tile * 1.9, m.tile * 1.9);
        }

        const s = f ? m.tile * (1 - 0.08 * Math.sin(f.t * Math.PI)) : m.tile;
        const off = (m.tile - s) / 2;
        roundRect(ctx, x + off, y + off, s, s, 10);
        if (on) {
          const g = ctx.createLinearGradient(x, y, x, y + m.tile);
          g.addColorStop(0, '#ffd775');
          g.addColorStop(1, '#e8991a');
          ctx.fillStyle = g;
        } else {
          const g = ctx.createLinearGradient(x, y, x, y + m.tile);
          g.addColorStop(0, '#2f3a55');
          g.addColorStop(1, '#232c42');
          ctx.fillStyle = g;
        }
        ctx.fill();
        ctx.strokeStyle = on ? 'rgba(255,255,255,.35)' : 'rgba(255,255,255,.07)';
        ctx.lineWidth = 1.5;
        ctx.stroke();

        if (on) {
          ctx.fillStyle = 'rgba(255,255,255,.3)';
          roundRect(ctx, x + m.tile * 0.16, y + m.tile * 0.14, m.tile * 0.68, m.tile * 0.2, 5);
          ctx.fill();
        }

        const i = idx(r, c);
        if (i === hintCell || (showSolution && solution[i])) {
          ctx.strokeStyle = i === hintCell ? '#4ad46f' : 'rgba(74,212,111,.55)';
          ctx.lineWidth = 3;
          ctx.setLineDash([6, 4]);
          roundRect(ctx, x + 3, y + 3, m.tile - 6, m.tile - 6, 8);
          ctx.stroke();
          ctx.setLineDash([]);
        }
      }
    }
  }

  /* ---------- menu ---------- */

  function showMenu() {
    state = 'menu';
    lights = new Array(N * N).fill(0);
    for (let i = 0; i < N * N; i++) lights[i] = (i * 7 + Math.floor(i / N) * 3) % 4 < 2 ? 1 : 0;
    Shell.status('', '');
    Shell.readouts([4, 5, 6].map((n) => ({ label: 'Best ' + n + 'x' + n, value: Scores.label('lights', 'n' + n) })));
    Shell.startCard({
      blurb: 'Every press flips a cross of lights. Turn them all off.',
      extra: `<div class="rowBetween"><span>Grid</span><div class="seg">${
        [3, 4, 5, 6].map((n) => `<button data-act="size" data-n="${n}" class="${N === n ? 'on' : ''}">${n}x${n}</button>`).join('')
      }</div></div>
      <div class="rowBetween"><span>Hint key</span><b style="color:var(--text)">H</b></div>`,
      buttons: [{ label: 'Play', act: 'again', primary: true }]
    });
  }

  Shell.on({
    again: () => newPuzzle(N),
    menu: () => showMenu(),
    size: (el) => { N = +el.dataset.n; showMenu(); }
  });

  Loop.start(() => {}, draw, { pauseOnHide: false });
  showMenu();

  window.EasyLights = {
    get state() { return state; },
    get presses() { return presses; },
    get minimum() { return minimum; },
    lights: () => lights,
    setLights(v) { lights = v.slice(); N = Math.round(Math.sqrt(v.length)); recomputeSolution(); },
    setN(n) { N = n; },
    solve, pressAt, newPuzzle, click, recomputeSolution,
    solution: () => solution
  };
})();
